Repository geekan/MetaGPT, pull requests merged in 2024-05, with the labels that each got.

#1268 fix openai image schema bug
  metagpt/provider/base_llm.py
Labels: Review effort [1-5]: 2, bug_fix

#1253 fix: failure when usage is none
  metagpt/provider/openai_api.py
Labels: Review effort [1-5]: 2, Bug fix

#1270 format
  metagpt/rag/benchmark/base.py
  metagpt/rag/factories/ranker.py
Labels: enhancement, Review effort [1-5]: 2

#1241 Make RAG embedding model dimension configurable
  config/config2.example.yaml
  metagpt/configs/embedding_config.py
  metagpt/rag/schema.py
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#1277 Pre-commit workflow添加environment，使之可以配置为分支合入时的保护
  .github/workflows/pre-commit.yaml
Labels: enhancement, Review effort [1-5]: 1

#1264 fix aask() got an unexpected keyword argument 'images'
  metagpt/provider/human_provider.py
Labels: Review effort [1-5]: 1, Bug fix

#1231 Feat add Amazon Bedrock support
  config/puppeteer-config.json
  metagpt/configs/llm_config.py
  metagpt/provider/__init__.py
  metagpt/provider/bedrock/__init__.py
  metagpt/provider/bedrock/base_provider.py
  metagpt/provider/bedrock/bedrock_provider.py
  metagpt/provider/bedrock/utils.py
  metagpt/provider/bedrock_api.py
  metagpt/utils/token_counter.py
  requirements.txt
  tests/metagpt/provider/mock_llm_config.py
  tests/metagpt/provider/req_resp_const.py
  tests/metagpt/provider/test_bedrock_api.py
Labels: enhancement, tests, Review effort [1-5]: 4

#1234 refactor: optimizing act_by_order mode of `Role`
  metagpt/roles/product_manager.py
  metagpt/roles/role.py
  tests/metagpt/roles/test_product_manager.py
Labels: enhancement, Review effort [1-5]: 2

#1279 Fix build failure
  requirements.txt
  setup.py
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#1258 [fix] stream field in llmconfig not work
  metagpt/configs/llm_config.py
  metagpt/provider/base_llm.py
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#1280 [example] bedrock config
  config/examples/aws-bedrock.yaml
Labels: enhancement, Review effort [1-5]: 2

#1207 add new android operation(open app,exit,stop)
  metagpt/environment/android/android_ext_env.py
  metagpt/environment/android/grounding_dino_config.py
  metagpt/environment/android/text_icon_localization.py
  metagpt/utils/common.py
  setup.py
Labels: Review effort [1-5]: 4

#1282 Fix/bedrock bugs
  metagpt/provider/bedrock/base_provider.py
  metagpt/provider/bedrock/bedrock_provider.py
  metagpt/provider/bedrock/utils.py
  metagpt/provider/bedrock_api.py
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#1300 feat: rename "Required Python packages" to "Required packages" for program language compatibility
  metagpt/actions/project_management.py
  metagpt/actions/project_management_an.py
  metagpt/actions/write_code_an_draft.py
  tests/data/rsp_cache.json
  tests/metagpt/actions/mock_json.py
Labels: enhancement
