Repository geekan/MetaGPT, pull requests merged in 2024-04, with the labels that each got.

#1137 fix api_version bug
  examples/werewolf_game/actions/experience_operation.py
Labels: bug-fix

#1148 fixbug: TypeError: _evaluate() got an unexpected keyword argument 'recursive_guard'
  requirements.txt
  setup.py
Labels: bug-fix

#1099 fixbug: #1095
  metagpt/actions/write_code_plan_and_change_an.py
  metagpt/actions/write_prd_an.py
  metagpt/roles/engineer.py
  metagpt/schema.py
Labels: bug-fix

#1103 fixbug: #1094
  metagpt/context.py
  metagpt/team.py
  tests/metagpt/serialize_deserialize/test_team.py
Labels: bug-fix

#1155 feat: add none
  metagpt/configs/mermaid_config.py
  metagpt/utils/mermaid.py
Labels: bug-fix

#1209 fixbug: action return None
  metagpt/roles/role.py
Labels: bug-fix

#1215 rename example file and add more logs. add ping.py
  examples/hello_world.py
  examples/ping.py
Labels: enhancement, tests, Review effort [1-5]: 3

#1212 fix bug for devcontainer; it should use metagpt/metagpt:latest
  .devcontainer/devcontainer.json
Labels: Review effort [1-5]: 1

#1217 update openai model version
  README.md
  config/config2.example.yaml
  config/config2.yaml
  config/examples/openrouter-wizardlm2-8x22b.yaml
  docs/FAQ-EN.md
  examples/debate_simple.py
  metagpt/software_company.py
  metagpt/utils/token_counter.py
  tests/config2.yaml
  tests/metagpt/test_context_mixin.py
  tests/metagpt/tools/test_ut_writer.py
  tests/metagpt/utils/test_cost_manager.py
Labels: enhancement, Review effort [1-5]: 2

#1221 Update requirements.txt to resolve dependency issues
  requirements.txt
Labels: enhancement, Review effort [1-5]: 2

#1224 Fix the potential duplicate embeddings in the RAG module
  examples/rag_pipeline.py
  metagpt/rag/engines/simple.py
  metagpt/rag/factories/base.py
  metagpt/rag/factories/retriever.py
  tests/metagpt/rag/engines/test_simple.py
  tests/metagpt/rag/factories/test_base.py
  tests/metagpt/rag/factories/test_retriever.py
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#1193 Feat:Add RAG Benchmark method
  examples/data/rag_bm/RGB_En/answer.json
  examples/data/rag_bm/RGB_En/documents.txt
  examples/data/rag_bm/dataset_info.json
  examples/data/rag_bm/simplified_CRUD/answer.json
  examples/data/rag_bm/simplified_CRUD/documents.txt
  examples/data/rag_bm/simplified_RGB/answer.json
  examples/data/rag_bm/simplified_RGB/documents.txt
  examples/rag_bm.py
  metagpt/const.py
  metagpt/rag/benchmark/__init__.py
  metagpt/rag/benchmark/base.py
  metagpt/rag/factories/ranker.py
  metagpt/rag/schema.py
  setup.py
Labels: Review effort [1-5]: 4

#1228 FIx:Correction of the calculation of the MRR indicator in the RAG benchmark
  metagpt/rag/benchmark/base.py
Labels: Review effort [1-5]: 2, bug_fix
