Repository geekan/MetaGPT, pull requests merged in 2024-01, with the labels that each got.

#497 add increment development function
  metagpt/actions/design_api.py
  metagpt/actions/design_api_an.py
  metagpt/actions/project_management.py
  metagpt/actions/project_management_an.py
  metagpt/actions/write_code.py
  metagpt/actions/write_code_plan_and_change_an.py
  metagpt/actions/write_code_review.py
  metagpt/actions/write_prd.py
  metagpt/actions/write_prd_an.py
  metagpt/const.py
  metagpt/roles/engineer.py
  metagpt/schema.py
  metagpt/utils/mermaid.py
  tests/data/incremental_dev_project/Gomoku.zip
  tests/data/incremental_dev_project/dice_simulator_new.zip
  tests/data/incremental_dev_project/mock.py
  tests/data/incremental_dev_project/number_guessing_game.zip
  tests/data/incremental_dev_project/pygame_2048.zip
  tests/data/incremental_dev_project/readme.md
  tests/data/incremental_dev_project/simple_add_calculator.zip
  tests/data/incremental_dev_project/snake_game.zip
  tests/data/incremental_dev_project/word_cloud.zip
  tests/metagpt/actions/test_design_api_an.py
  tests/metagpt/actions/test_project_management_an.py
  tests/metagpt/actions/test_write_code_plan_and_change_an.py
  tests/metagpt/actions/test_write_prd_an.py
  tests/metagpt/test_incremental_dev.py
Labels: features

#799 Solve JSONDecodeError
  metagpt/utils/repair_llm_raw_output.py
  tests/metagpt/utils/test_repair_llm_raw_output.py
Labels: bug-fix

#801 Refactor get_choice_delta_text for safer dict access while using ZHIPU API
  metagpt/provider/base_llm.py
Labels: todo
